language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
before_install:
- pip3 install codecov
install:
  - "pip3 install -r requirements-dev.txt"
after_success:
  - codecov
script: coverage run -m unittest discover
